version: '3.9'

services:
  students_db:
    container_name: students_db
    image: mysql:8.2.0
    restart: always
    environment:
      - MYSQL_DATABASE=studentsDb
      - MYSQL_PASSWORD=root123
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - '3306'

  courses_db:
    container_name: courses_db
    image: postgres:15-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=coursesDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
    ports:
      - '5432:5432'
    expose:
      - '5432'