server:
  port: 9090

spring:
  application:
    name: ms-course
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/coursesDb
    username: root
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka