eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
        - id: students
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**